apiVersion: v1
kind: ConfigMap
metadata:
  name: massimo-app-config
data:
  VITE_API_URL: "https://api.massimo.global"
  VITE_APP_LOGO_URL: "https://plus.unsplash.com/premium_photo-1664474619075-644dd191935f?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2069"
  VITE_APP_NAME: "Massimo App"